### ISSUE TITLE
Internal Server Error bei falschem Pfad

### ISSUE THREAD

**Issue by brt-tito** [ynamite/massif_minify#1]
Wenn ich in den Einstellungen einen Pfad, z.B. zur CSS-Datei, eintrage, der nicht existiert, dann bekomme ich einen Fehler 500 - Internal Server Error. 
edit: Bin mir jetzt nicht mehr sicher, ob es der Pfad alleine ist. Habe wieder einen 500er bekommen, diesmal bei richtigen Pfaden. Nachdem ich CSS- und JS-Komprimieren deaktiviert habe ging es wieder.
Redaxo 5.2.0 / PHP 5.6.30

**Comment by ynamite** [comment]
Wozu verwendest du massif_minify? Um SCSS zu kompilieren? Falls ja, teste mal ein einziges sehr rudimentäres/leeres SCSS file (alle anderen Files aus dem angegebenen SCSS Ordner löschen) und gib Bescheid ob's damit klappt. Ich vermute es hängt mit fehlenden SASS Dependencies zusammen.

Falls nicht, was genau möchtest du tun?

**Comment by brt-tito** [comment]
Wollt's halt mal ausprobieren weil's angeboten wird ;-)
Ist aber nicht so wichtig, ich verwende in der betroffenen Installation jetzt das minfiy-Addon. Kannst gerne zumachen ... oder ich versuche, das irgendwann noch einmal zu testen.

**Comment by ynamite** [comment]
@brt-tito Easy, kein Problem ;) Ich meinte nur ob du mir sagen kannst welche Funktionen (HTML/CSS/SCSS/JS) du genutzt bzw. eingebunden hattest, nicht wieso du das Addon grundsätzlich verwendest :) Würde gerne herausfinden woran's gelegen hat.

Danke dir!

**Comment by ynamite** [comment]
Da hier keine Rückmeldung kommt schliesse ich das mal. Wenn weitere Infos vorliegen kann das gerne weiterverfolgt werden.
