### ISSUE TITLE
Error nach Update auf Redaxo 5.9

### ISSUE THREAD

**Issue by rolandsee** [ynamite/massif_minify#10]
Letzte funktionierende Redaxo-Version ist 5.8.1. Nach dem Update auf 5.9.0 kommt diese Fehlermeldung.
![image](https://user-images.githubusercontent.com/4113894/73665402-4f293100-46a1-11ea-8dae-db00c35871d9.png)

**Comment by schuer** [comment]
https://github.com/ynamite/massif_minify/blob/f0d2751c2fcbe55a200ff81f097138af43902f7a/lib/class.massif_minify.php#L16-L17

Das Package wurde verschoben/umbenannt. Statt `Leafo\ScssPhp` ist es nun `ScssPhp\ScssPhp`.

**Comment by rolandsee** [comment]
Yep, so habe ich das AddOn auch wieder zum Laufen bekommen:

```
use ScssPhp\ScssPhp\Compiler;
use ScssPhp\ScssPhp\Formatter;
use MatthiasMullie\Minify;
	

class scss_formatter extends \ScssPhp\ScssPhp\Formatter\Expanded
{
}
```

**Comment by ynamite** [comment]
@schuer



> https://github.com/ynamite/massif_minify/blob/f0d2751c2fcbe55a200ff81f097138af43902f7a/lib/class.massif_minify.php#L16-L17
> 
> Das Package wurde verschoben/umbenannt. Statt `Leafo\ScssPhp` ist es nun `ScssPhp\ScssPhp`.

@schuer weisst du gerade wie ich prüfen kann, welches Package vorhanden ist, bevor ich `use` verwende? Zwecks Rückwärtskompatibilität?
