### ISSUE TITLE
Plugin funktioniert leider nicht

### ISSUE THREAD

**Issue by maydaypipe** [ynamite/massif_minify#11]
Neustes Redaxo installiert, alles auf dem neusten Stand. Htaccess mehrmals angepasst und mit Base und ohne versucht. Hat leider absolut nicht funktioniert oder die Beschreibung ist unvollständig, wovon ich jetzt nicht ausgehe.

**Comment by ynamite** [comment]
Was genau funktioniert nicht? Ohne genauere Angaben kann ich leider nicht helfen.
Wie sieht dein Code aus? Gibt es eine Fehlermeldung? Apache oder nginx?

**Comment by maydaypipe** [comment]
HTML wird zwar komprimiert aber die CSS und JS Dateien werden leider nicht komprimiert. 
Es werden keine Fehlermeldungen ausgegeben.
Nutze Apache und PHP 7.4 sowie neuste Redaxo Version. 


<html lang="<?php echo rexx::getLangCode(); ?>">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <base href="<?php echo rexx::getBaseUrl(); ?>" />
    
    <title><?php echo rexx::getTitlePart(); ?></title>
    <meta name="description" content="<?php echo rexx::getDescription(); ?>" />
    <meta name="keywords" content="<?php echo rexx::getKeywords(); ?>" />
    <meta name="robots" content="<?php echo rexx::getRobotRules();?>" />
    <?php echo rexx::getLangTags(); ?>

    <link rel="canonical" href="<?php echo rexx::getCanonicalUrl(); ?>" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&amp;subset=cyrillic" rel="stylesheet">
    <link rel="stylesheet" href="css/bootstrap.min.css" />
    <link rel="stylesheet" href="source/fontawesome/css/all.css" />
    <link rel="stylesheet" href="css/style.css" />



<script src="js/jquery.min.js" type="text/javascript"></script>
    <script src="js/bootstrap.min.js" type="text/javascript"></script>
    <script src="js/bootstrap.bundle.min.js" type="text/javascript"></script>
    <script src="js/cookiebar.js" type="text/javascript"></script>
    <script src="js/script.js" type="text/javascript"></script>

**Comment by ynamite** [comment]
Kann es sein, dass du die Anleitung überlesen hast? 
Sehe in deinem Code keine Verwendung von massif_minify ... ?

Hier auf Github steht bei "Installation":
> In den gewünschten Templates die gewünschte Addon Methode aufrufen, siehe Beispiele unter "Anleitung" im Addon

**Comment by maydaypipe** [comment]
Guten Morgen und vielen Dank für deine schnelle Reaktion. So schnell hatte ich mit eine Antwort nicht gerechnet.

OK dann hatte ich die Beschreibung doch falsch verstanden. Dachte ich muss nichts einbinden, solange die Häkchen aktiviert sind und wenn ich die manuell einbinden will, muss ich die Häkchen deaktivieren. 

Nun klappt doch alles perfekt.

**Comment by ynamite** [comment]
Kein Problem, freut mich das es nun klappt :)
