### ISSUE TITLE
Glue String 

### ISSUE THREAD

**Issue by webregie** [ynamite/massif_minify#12]
Ich habe mal PHP 7.4 versucht und lese im Error Log: 

29.09.2020 15:55:50 | Deprecated | implode(): Passing glue string after array is deprecated. Swap the parameters | redaxo/src/addons/massif_minify/vendor/minify/src/CSS.php | 528
-- | -- | -- | -- | --

**Comment by fietstouring** [comment]
https://github.com/matthiasmullie/minify/pull/300

**Comment by ynamite** [comment]
fixed:
https://github.com/ynamite/massif_minify/commit/52a9a46328fea369384fbb45d8db6fbb977d5d49
