### ISSUE TITLE
Update auf REX 5.13

### ISSUE THREAD

**Issue by webregie** [ynamite/massif_minify#13]
AddOn massif_minify meldet: Das AddOn be_style (Version 3.0.0) entspricht nicht der geforderten Versionsbedingung ^2.9.0!

Jetzt muss ich erstmal schauen wo das be_style im massiv_minify steht...

**Comment by ynamite** [comment]
in der package.yml.
Werde ASAP einen Fix veröffentlichen, danke für die Info!

**Comment by ynamite** [comment]
fixed:
https://github.com/ynamite/massif_minify/commit/52a9a46328fea369384fbb45d8db6fbb977d5d49
