### ISSUE TITLE
Multidomainfähigkeit

### ISSUE THREAD

**Issue by danspringer** [ynamite/massif_minify#14]
Wenn man mittels YRewrite mehrere Domains betreibt und z.B. wie folgt eine SCSS zum Compilen einbindet, wird in einer "Nebendomain" ein absoluter Pfad zur "Hauptdomain" der Redaxo-Installation ausgegeben, was nicht korrekt ist. 

Wenn man hier einfach 
`return rtrim(rex::getServer(), "/") . self::$cssOutDir . self::getFileWithVersionParam($file, self::$cssOutPath);`
gegen
`return self::$cssOutDir . self::getFileWithVersionParam($file, self::$cssOutPath);`
austauscht, scheint es zu funktionieren. Ob der relative Pfad Nachteile hat, konnte ich noch nicht feststellen.

https://github.com/ynamite/massif_minify/blob/master/lib/class.massif_minify.php#L113

**Comment by ynamite** [comment]
@danspringer Danke für das Issue, guck ich mir gleich morgen  an. 

Werde wohl eine Abfrage für yrewrite einbauen und dann gleich die aktive Domain auslesen, falls vorhanden, dann passt das.

Wenn du übrigens lieber relative Pfade verwenden möchtest, kannst du dafür auch die Einstellung für absolute Pfade in den Addon-Einstellungen deaktivieren. 

FYI hab gerade kurz nachgesehen, in meinen Projekten hab ich immer relative Pfade eingestellt und soweit keine Probleme.

**Comment by ynamite** [comment]
fixed with
https://github.com/ynamite/massif_minify/commit/c881b0089c191a726c36054e7954c6dec0cf31c8
