### ISSUE TITLE
getCombinedCSSMinFile Probleme mit calc und CSS variables?

### ISSUE THREAD

**Issue by fietstouring** [ynamite/massif_minify#16]
habe folgendes CSS bei mir stehen:
`padding: 0 calc(var(--grid-gutter-width) / 2) calc(var(--grid-gutter-width) / 2); `

die Funktion getCombinedCSSMinFile macht dann das draus:
`padding: 0 calc(var(--grid-gutter-width) / 2); `

musste die Werte dann separat setzen um das richtige Ergebnis zu erzielen:
```
padding-top: 0;
padding-left: calc(var(--grid-gutter-width) / 2);
padding-right: calc(var(--grid-gutter-width) / 2);
padding-bottom: calc(var(--grid-gutter-width) / 2);
```

**Comment by ynamite** [comment]
Ich meine das liegt weniger an massif_minify als an scssphp (vendor library) oder der Minifizierungs Library (ebenfalls vendor library).

Folgendes ginge sonst auch:
``` 
.test {
    --grid-gutter-width-half: calc(var(--grid-gutter-width) / 2);
    padding: 0 var(--grid-gutter-width-half) var(--grid-gutter-width-half);
}
```

**Comment by ynamite** [comment]
keine Rückmeldung, schliesse deshalb hier
