### ISSUE TITLE
Umstellung auf PHP 8.1 erzeugt deprecated Meldungen

### ISSUE THREAD

**Issue by HassChristian** [ynamite/massif_minify#17]
Moin!

Mit der Umstellung auf PHP 8.1 oder höher tauchen in den Logdateien zwei Meldungen auf:

1. Creation of dynamic property Minify_HTML::$_html is deprecated
    redaxo/src/addons/massif_minify/vendor/Minify_HTML.php:69

2. Use of "parent" in callables is deprecated
    redaxo/src/addons/massif_minify/vendor/minify/src/JS.php:129

**Comment by ynamite** [comment]
Tach!

Meinst du im System Log von Redaxo? Zumindest dort ist das bei mir definitiv nicht der Fall. Ich verwende massif_minify zusammen mit PHP 8.1 in diversen Projekten. 

Schau es mir aber gerne genauer an :)

**Comment by HassChristian** [comment]
![Screenshot 2023-03-18 at 17-56-32 REDAXO · Christian Haß · REDAXO CMS](https://user-images.githubusercontent.com/26849978/226173448-0c6b53f6-363c-4098-9b42-497c41d4abea.png)

Habe mich oben verschrieben. Mit Version 8.2 tritt es auf. Siehe Screenshot.

**Comment by ynamite** [comment]
Auf Git steht eine neue Version bereit. Magst du mal testen, ob sich die Meldungen bei dir damit verabschiedet haben?
Falls ja, würde ich die neue Version anschliessend in den Installer laden.

**Comment by HassChristian** [comment]
Habs getestet. Bir mir läuft es jetzt ohne Probleme.

**Comment by ynamite** [comment]
Perfekt! Ist ab sofort im Installer :)
