### ISSUE TITLE
LESS + HTML compress

### ISSUE THREAD

**Issue by ghost** [ynamite/massif_minify#3]
Hallo
es wäre super wenn es einen LESS Compiler + LESS Komprimierung gäbe.
Außerdem wenn man eine CSV Datei generieren + zum download VIA php anbieten will, funktioniert dies nicht, weil hierbei auch eine Komprimierung statt findet. Also wäre es noch super wenn eine Komprimierung einer bestimmten Datei ausgeschlossen werden kann.

**Comment by ynamite** [comment]
Hi @clicksports 

Vielen Dank für den Hinweis betreffend CSV. Schaue ich mir bei nächster Gelegenheit an.

LESS kann relativ einfach eingebunden werden, darfst gerne einen PR dazu machen, dann bau ich das mitein. Selbst werde ich das wohl aber nicht realisieren, benötige ich schlichtweg nicht, sorry :)

**Comment by ynamite** [comment]
Betreffend CSV, ich glaube es macht mehr Sinn den CSV-Export so zu programmieren, dass dieser vor dem Extension Point OUTPUT_FILTER mit "rex_extension::LATE" greift und somit hier keine Probleme entstehen.

Ich wüsste nicht wie ich im Extension Point den Dateityp erkennen könnte :/ 

Bin offen für Vorschläge!
