### ISSUE TITLE
getJSCodeFromTemplate Fehler bei compress 

### ISSUE THREAD

**Issue by fietstouring** [ynamite/massif_minify#4]
Ich hab da in meinem JS folgende Variable drin:

`var x = $('a[href^="#"]:not(.no-scroll)');`

In der compressed Ausgabe mit der Funktion massif_minify::getJSCodeFromTemplate(id, true); fehlt alles in der Zeile was nach dem Hash # kommt.

`$('a[href^="`

**Comment by ynamite** [comment]
@fietstouring 
Habe soeben einen Fix auf Git veröffentlich (https://github.com/ynamite/massif_minify/commit/b2ebd03322aec262a640585da1665ad9b9a69d99).

Kannst du das kurz testen und mir Bescheid geben, ob's klappt? Bin gerade ziemlich im Stress. Thx!

**Comment by fietstouring** [comment]
Danke!
Fix scheint zu funktionieren.

**Comment by ynamite** [comment]
Noice! Danke für die Rückmeldung.
