### ISSUE TITLE
getCSSCodeFromTemplate

### ISSUE THREAD

**Issue by fietstouring** [ynamite/massif_minify#5]
Ich verwende in letzter Zeit oft inline CSS im `<head>`, welches ich in ein template packe.
Dafür hab ich zwei der Funktionen in massif_minify kopiert und angepasst, damit man das auch minifyen kann. Vielleicht willst Du das hinzufügen.

```
public static function getCSSCodeFromTemplate($templateId, $simpleMinify = true) {
		$template = new rex_template($templateId);

		return self::getCSSCode($template->getFile(), $simpleMinify);
	}

	protected static function getCSSCode($includeFileWithPath, $simpleMinify = true) {
		$interpretedPhp = '';

		// interpret css as php
		ob_start();

		@include($includeFileWithPath);
		$interpretedPhp = ob_get_contents();

		ob_end_clean();

		if ($simpleMinify) {
			$interpretedPhp = self::getMinifiedContent($interpretedPhp, 'css');
		} 

		return $interpretedPhp;
	}
```

**Comment by ynamite** [comment]
Hatte das Problem letztens auch und hab das ähnlich gelöst (bzw. hab den inline-Minifier angepasst). Kommt in der nächsten Version, danke für den Hinweis!
