### ISSUE TITLE
Minifier funktioniert nicht mit Search it

### ISSUE THREAD

**Issue by danspringer** [ynamite/massif_minify#6]
Da der Minifier HTML-Kommentare auch entfernt, bleibt der der Such-Index von Search it bei der Indizierung leer.

Während der Indizierung ruft Search it den jeweiligen Artikel mit dem leeren Parameter 'search_it_build_index' auf und setzt temporär HTML-Kommentare in den Quelltext für die Stellen, die aufgenommen werden .

Ich habe in 'lib > class.massif_minify.php' in Zeile 47 das ergänzt:

```
$search_it_indexer = rex_get('search_it_build_index','string');
		$search_it_highlighter = rex_get('search_highlighter','string');
		if($search_it_indexer == "" && $search_it_highlighter != "") {
			$search_it_indexer = 'search_it_highlighter';
			}
```

und aus Zeile 84 das gemacht:

`if ($addon->getConfig('minify_html') && !rex::isBackend() && $search_it_indexer == "") {`

Ich bin mir nicht sicher, ob das so "schön" ist, aber der Indexaufbau von Search it funktioniert jetzt und im Frontend wird trotzdem alles noch hübsch komprimiert ausgegeben.

Evtl. kannst du das bei ner neuen Version im Hinterkopf behalten :-)

**Comment by ynamite** [comment]
Danke für den Hinweis, schau ich mir an.
Ich denke ich würde das ähnlich handhaben.

**Comment by ynamite** [comment]
https://github.com/ynamite/massif_minify/commit/b1bcb08e12380747241d1096f70c565e602b702f

Addon wurde soeben auf Github aktualisiert. Bitte testen :)
