### ISSUE TITLE
Slash nur bei Bedarf

### ISSUE THREAD

**Issue by webregie** [ynamite/massif_minify#7]
Ich nutze gerne volle URLs und hole mir  `rex::getServer()` (Es gibt Vorteile!)
Da ist der / Slash am Ende dabei. 

In den Einstellungen von Minify habe ich die resources/css und resources/js jeweils ohne Slash zu Beginn angegeben. 
Aufgerufen:
'<link rel="stylesheet" href="<?php echo rex::getServer().massif_minify::getCombinedCSSMinFile("styles_combined.css", array(....)'

Allerdings hat man in der Ausgabe dann eine URL mit `https://www.domain.de//resources/css/mini_datei.css`

Kann man das nicht so gestalten, dass die Einstellungen entscheidend sind? 

Dank und Gruß 
Ralf

**Comment by ynamite** [comment]
@webregie Würde es deiner Meinung nach Sinn machen, beim Aufruf einer Ressource rex::getServer() gleich standardmässig mitzugeben? 

Was sind denn aus deiner Sicht die Vorteile? Würde mich interessieren.
Ist mir auch recht wenn das für alle Anwender logischer ist :) 

PS. nur für den Fall, vorläufige Abhilfe schafft folgendes: 
```<link rel="stylesheet" href="<?=rtrim(rex::getServer(), "/").massif_minify::getCombinedCSSMinFile("styles_combined.css", array(....)```

**Comment by webregie** [comment]
@ynamite Vielen Dank für die schnelle Antwort. Ich denke nicht, dass es sinnvoll ist gleich rex::getServer() mitzugeben. Das wäre für andere sicher wieder negativ. Ich fände die Entscheidung sinnvoll. 
Für SEO und Contentklau gibt es allerdings Vorteile. Das sollte jeder selbst ausprobieren und danach googlen oder andersrum. Das sollte man dann auch für interne Links verwenden.
Vielen Dank für deinen Trim-Tip. ;)

**Comment by ynamite** [comment]
https://github.com/ynamite/massif_minify/commit/b1bcb08e12380747241d1096f70c565e602b702f

Addon wurde soeben auf Github aktualisiert. Bitte testen :)
