### ISSUE TITLE
Analytics FOR und HTML Kompressor

### ISSUE THREAD

**Issue by webregie** [ynamite/massif_minify#8]
... arbeitet nicht mit dem Code zusammen. Irgendwas wird herausgekürzt, sodass Analytics dann gar nicht mehr zählt.

https://github.com/FriendsOfREDAXO/analytics/issues/28

**Comment by ynamite** [comment]
https://github.com/ynamite/massif_minify/commit/b1bcb08e12380747241d1096f70c565e602b702f

Addon wurde soeben auf Github aktualisiert. Bitte testen :)

**Comment by ynamite** [comment]
Kein Feedback mehr, ich schliesse mal.
